name: Build and Generate Checksums
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Generate Checksums
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Build Executables
        run: make build-all
